# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.engine.proto import game_engine_pb2 as meeple_dot_game__engine_dot_v1_dot_game__engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meeple/game_engine/v1/game_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameEngineServiceStub(object):
    """--- Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameInfo = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/GetGameInfo',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoResponse.FromString,
                _registered_method=True)
        self.ListGames = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/ListGames',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesResponse.FromString,
                _registered_method=True)
        self.CreateInitialState = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/CreateInitialState',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateResponse.FromString,
                _registered_method=True)
        self.GetValidActions = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/GetValidActions',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsResponse.FromString,
                _registered_method=True)
        self.ValidateAction = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/ValidateAction',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionResponse.FromString,
                _registered_method=True)
        self.ApplyAction = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/ApplyAction',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionResponse.FromString,
                _registered_method=True)
        self.GetPlayerView = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/GetPlayerView',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewResponse.FromString,
                _registered_method=True)
        self.GetSpectatorSummary = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/GetSpectatorSummary',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryResponse.FromString,
                _registered_method=True)
        self.StateToAiView = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/StateToAiView',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewResponse.FromString,
                _registered_method=True)
        self.ParseAiAction = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/ParseAiAction',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionResponse.FromString,
                _registered_method=True)
        self.OnPlayerForfeit = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/OnPlayerForfeit',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitResponse.FromString,
                _registered_method=True)
        self.MctsSearch = channel.unary_unary(
                '/meeple.game_engine.v1.GameEngineService/MctsSearch',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchResponse.FromString,
                _registered_method=True)
        self.RunArena = channel.unary_stream(
                '/meeple.game_engine.v1.GameEngineService/RunArena',
                request_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.RunArenaRequest.SerializeToString,
                response_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ArenaProgressUpdate.FromString,
                _registered_method=True)


class GameEngineServiceServicer(object):
    """--- Service ---

    """

    def GetGameInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInitialState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpectatorSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StateToAiView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseAiAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPlayerForfeit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MctsSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunArena(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameInfo,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoResponse.SerializeToString,
            ),
            'ListGames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGames,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesResponse.SerializeToString,
            ),
            'CreateInitialState': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInitialState,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateResponse.SerializeToString,
            ),
            'GetValidActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidActions,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsResponse.SerializeToString,
            ),
            'ValidateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAction,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionResponse.SerializeToString,
            ),
            'ApplyAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAction,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionResponse.SerializeToString,
            ),
            'GetPlayerView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerView,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewResponse.SerializeToString,
            ),
            'GetSpectatorSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpectatorSummary,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryResponse.SerializeToString,
            ),
            'StateToAiView': grpc.unary_unary_rpc_method_handler(
                    servicer.StateToAiView,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewResponse.SerializeToString,
            ),
            'ParseAiAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseAiAction,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionResponse.SerializeToString,
            ),
            'OnPlayerForfeit': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPlayerForfeit,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitResponse.SerializeToString,
            ),
            'MctsSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.MctsSearch,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchResponse.SerializeToString,
            ),
            'RunArena': grpc.unary_stream_rpc_method_handler(
                    servicer.RunArena,
                    request_deserializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.RunArenaRequest.FromString,
                    response_serializer=meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ArenaProgressUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meeple.game_engine.v1.GameEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meeple.game_engine.v1.GameEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameEngineService(object):
    """--- Service ---

    """

    @staticmethod
    def GetGameInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/GetGameInfo',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetGameInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/ListGames',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ListGamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInitialState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/CreateInitialState',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.CreateInitialStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/GetValidActions',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetValidActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/ValidateAction',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ValidateActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/ApplyAction',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ApplyActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/GetPlayerView',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetPlayerViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpectatorSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/GetSpectatorSummary',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.GetSpectatorSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StateToAiView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/StateToAiView',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.StateToAiViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseAiAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/ParseAiAction',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ParseAiActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPlayerForfeit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/OnPlayerForfeit',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.OnPlayerForfeitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MctsSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/MctsSearch',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.MctsSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunArena(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meeple.game_engine.v1.GameEngineService/RunArena',
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.RunArenaRequest.SerializeToString,
            meeple_dot_game__engine_dot_v1_dot_game__engine__pb2.ArenaProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
